### ISSUE TITLE
Run one liner command

### ISSUE THREAD

**Issue by Arno0x** [p3nt4/PowerShdll#1]
Hi,

Is it possible to pass some arguments such that it can execute, for instance, an encoded payload ? Something like:

`rundll32.exe PowerShDll,main -enc <encoded_payload>`

Thx.

**Comment by p3nt4** [comment]
I tried to parse arguments from rundll32 but couldnt manage to make it work. I am wrapping c# code into an unmanaged assembly so that may be the reason. Feel free to submit a pull request if you manage to make it work.

**Comment by p3nt4** [comment]
You could easily modify the source code though, so that it would execute your payload directly instead of spawning a shell.

**Comment by p3nt4** [comment]
Hey, please checkout PowerShdll v0.2, it now supports inline scripts.
