### ISSUE TITLE
Error in PowerShdlldll entry missing "main"

### ISSUE THREAD

**Issue by mpgn** [p3nt4/PowerShdll#12]
Hello,

Any idea why when I compile the dll projet after a git clone I have this error:

![image](https://user-images.githubusercontent.com/5891788/109136408-5f062e00-7758-11eb-8bd6-42311a7c6a61.png)

**Comment by p3nt4** [comment]
Did you make any changes to the config?

Try reinstalling the UnmanagedExports NuGet package.
