### ISSUE TITLE
Missing Entry: Main 

### ISSUE THREAD

**Issue by chrisjd20** [p3nt4/PowerShdll#13]
Trying to figure out why I can't seem to have a working build. VS community 2019.

![image](https://user-images.githubusercontent.com/11812223/125669830-5b6ee21b-d403-4307-a761-3d39dec93035.png)
![image](https://user-images.githubusercontent.com/11812223/125669652-a017444b-d5b9-44fd-897b-3da5ed44b423.png)

As you can see from the pic, it successfully builds. I even delete the dlls and rebuild and build works fine.

But then it says `Missing entry: main`.

**Comment by p3nt4** [comment]
Try reinstalling the Nuget package, "Unmanaged Exports"

**Comment by p3nt4** [comment]
Do you have the same issue with the x64 version?

**Comment by chrisjd20** [comment]
So first I tried x64 and it does the same thing. Then I tried to reinstall:

![image](https://user-images.githubusercontent.com/11812223/125674010-1455ad9f-e736-43bf-b2a7-43ec83ce291e.png)
Then:
![image](https://user-images.githubusercontent.com/11812223/125674153-9fa16ce9-ad7f-41e2-b33b-f6a8c552097d.png)

Now it fails all together:

```
1>------ Build started: Project: PowerShdll, Configuration: Release x64 ------
1>  PowerShdll -> C:\Users\cdavis\Desktop\PowerShdll-master\PowerShdll-master\dll\bin\x64\Release\PowerShdll.dll
1>C:\Users\cdavis\Desktop\PowerShdll-master\PowerShdll-master\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4062: The "RGiesecke.DllExport.MSBuild.DllExportAppDomainIsolatedTask" task could not be loaded from the assembly C:\Users\cdavis\Desktop\PowerShdll-master\PowerShdll-master\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.MSBuild.dll. Could not load file or assembly 'Microsoft.Build.Utilities, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by chrisjd20** [comment]
Oh, do I need to have .NET 3.5 installed?

**Comment by chrisjd20** [comment]
Oh yea that's what it was! Just had to install  .NET 3.5.

I'm on Server 2019 so I had to `DISM /Online /Enable-Feature /FeatureName:NetFx3 /All`
