### ISSUE TITLE
-enc equivalent?

### ISSUE THREAD

**Issue by CaledoniaProject** [p3nt4/PowerShdll#4]
Is it possible to pass base64 encoded powershell commands?
Similar to `powershell -ep bypass -nop -enc XXXXXX`

**Comment by p3nt4** [comment]
Hey, It would be easy to implement but it is not necessary IMO.
Just use something like this:
```
rundll32 Powershdll.dll,main $a = [System.Text.Encoding]::ASCII.GetString([System.Convert]::FromBase64String("BASE64")); Invoke-Expression $a
```
Should do the trick.

**Comment by CaledoniaProject** [comment]
Thanks, I get your point.
