### ISSUE TITLE
DotNet 2.0 support?

### ISSUE THREAD

**Issue by CaledoniaProject** [p3nt4/PowerShdll#5]
I can't compile PowerShdll with .net framework 2.0 version, is it possible to add support for that?

On Windows 2008, .net framework 3.5 is not installed by default.

**Comment by p3nt4** [comment]
Do you have the System.Management.Automation.dll library? What error do you get?

**Comment by CaledoniaProject** [comment]
VS 2016 shows the following error:

<img width="728" alt="screenshot 2017-09-04 at 19 08 02" src="https://user-images.githubusercontent.com/1357701/30024014-760246fe-91a4-11e7-96ca-035798004443.png">

**Comment by p3nt4** [comment]
I have updated the .Net requirements to be 2.0 for Exe mode and 3.5 for dll mode.

I reckon the unamnaged exports library prevents using and older version of the .Net framework for dll mode.
