### ISSUE TITLE
There will be problems with execution on windows7

### ISSUE THREAD

**Issue by DSKYA** [p3nt4/PowerShdll#6]
Hello, friend!
This is a very useful project. 
I had a problem with executing code on windows7，“Run32dll stops working”.But it's okay to execute code on windows10.
Does this project not support the Windows7 operating system?

**Comment by p3nt4** [comment]
Hey, should work on windows 7. Can you give me more context? Do you have .Net installed? Did you try the exe mode?

**Comment by p3nt4** [comment]
I have updated the target frameworks to 2.0 and 3.5 for exe and dll modes. It should work now.
