### ISSUE TITLE
about windows 7 32bit

### ISSUE THREAD

**Issue by DSKYA** [p3nt4/PowerShdll#9]
When I executed this code on windows7 32bit, there is a problem.
:
  Stopped working
:
  problem name:	APPCRASH
  Application Name:	rundll32.exe
  Application Version:	6.1.7600.16385
  Application Timestamp:	4a5bc637
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.17514
  Fault Module Timestamp:	4ce7b8f0
  Exception Code:	e0434f4d
  Exception Offset:	0000b760
  OS :	6.1.7601.2.1.0.256.48
  area ID:	2052

**Comment by p3nt4** [comment]
Can you give details about the environment?
Which Powershdll version you are using? Which release? Are you using the 32 bits dll? 
What .Net framework version is installed? 
In what context are you running the application? Command line? VBS?

**Comment by DSKYA** [comment]
Thank you.I have solved this problem just now by using a lower version Nuget package.
When EXE is able to execute correctly, I find that there is a problem with the DLL export.
